### ISSUE TITLE
Assert jsonFileContent key with null value

### ISSUE THREAD

**Issue by alallier** [yeoman/yeoman-assert#21]
When testing assert.jsonFileContent('path/to/file.json', {a: null}); in the case when the key `a` has a value of `null` outputs this error:

```
TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at Function.assert.objectContent (node_modules\yeoman-assert\index.js:208:10)
      at node_modules\yeoman-assert\index.js:210:14
      at Array.forEach (native)
      at Function.assert.objectContent (node_modules\yeoman-assert\index.js:208:24)
      at node_modules\yeoman-assert\index.js:210:14
      at Array.forEach (native)
      at Function.assert.objectContent (node_modules\yeoman-assert\index.js:208:24)
      at Function.assert.JSONFileContent.assert.jsonFileContent (node_modules\yeoman-assert\index.js:243:10)
      at unitTest.js:20:18
```

**Comment by alallier** [comment]
Thanks for the quick fix! Just tried it again and it error with the following:

```
TypeError: Cannot read property 'keyPath' of undefined
      at node_modules\yeoman-assert\index.js:231:24
      at Array.forEach (native)
      at Function.assert.noObjectContent (node_modules\yeoman-assert\index.js:225:24)
      at node_modules\yeoman-assert\index.js:227:14
      at Array.forEach (native)
      at Function.assert.noObjectContent (node_modules\yeoman-assert\index.js:225:24)
      at unitTest.js:20:18
```

**Comment by SBoudrias** [comment]
@alallier Are you sure the json file you're asserting against exists?

**Comment by alallier** [comment]
Yes it does, I am checking it with other assertions in the same test. I only have a problem when I am checking the value `null`. If I change that same key to `false` and change my assertion to check false, I am fine

**Comment by alallier** [comment]
I just tested this in a small example and it seems to be working. I'll look at what I was originally working on and see if I can find what is going on.

**Comment by alallier** [comment]
Confirmed working now. Thank you so much for your time!!
